name: Cypress Automation

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run test:ci

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: cypress/reports/
